env:
  decimation: 1
  episode_length: 3.0 # seconds
  action_space: 7
  obs_space: 18
  rewards:
    sparse_height_bonus_threshold: 0.30
    orient_alignment_coef: 0.25
    cube_height_coef: 0.0
    sparse_height_bonus_coef: 20.0
    ee_prismatic_vel_coef: 0.05
    cube_z_vel_coef: 1.0
    dist_penalty_coef: -0.05
    passive_penalty_coef: -0.0001

scene:
  num_envs: 9
  env_spacing: 2.0
  replicate_physics: True
  clone_in_fabric: True
  light:
    intensity: 3000
    color: [0.75, 0.75, 0.75]
  cube:
    size: [0.07, 0.07, 0.07] # [m]
    diffuse_color: [1.0, 0.0, 0.0]
    pos: [0.4, 0.0, 0.1]
  marker:
    translation: 0.4
    scale: [0.2, 0.2, 0.6]

sim:
  dt: 0.01
  render_interval: 2

rl:
  epochs: 10
  iterations: 100
  batch_size: 32
  rollout_length: 512
  ppo:
    log_std_min: -20.0
    log_std_max: 2.0
    policy_lr: 0.001
    value_lr: 0.001
    value_coef: 0.5
    entropy_coef: 0.005
    discount_factor: 0.99
    gae_decay: 0.98
    clipping_param: 0.2