env:
  decimation: 1
  episode_length: 5.0 # [sec]
  action_space: 7
  obs_space: 18

scene:
  num_envs: 1024
  env_spacing: 2.0
  replicate_physics: True
  clone_in_fabric: True
  light:
    intensity: 3000
    color: [0.75, 0.75, 0.75]
  cube:
    size: [0.2, 0.2, 0.2] # [m]
    diffuse_color: [1.0, 0.0, 0.0]
    pos: [0.0, 1.0, 0.0]

sim:
  dt: 0.01
  render_interval: 2

rl:
  epochs: 10
  iterations: 20
  batch_size: 64
  rollout_length: 128
  ppo:
    log_var_min: -20.0
    log_var_max: 2.0
    policy_lr: 0.001
    value_lr: 0.001
    value_coef: 0.5
    entropy_coef: 0.005
    discount_factor: 0.99
    gae_decay: 0.98
    clipping_param: 0.2